// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLJ6Mr2QV9L2wry-hPXjxdfsd2qYEs2eM',
    appId: '1:88197098485:web:0af32d4586549893f10ebc',
    messagingSenderId: '88197098485',
    projectId: 'money-mate-608fd',
    authDomain: 'money-mate-608fd.firebaseapp.com',
    storageBucket: 'money-mate-608fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaTPMtxmixQ5RCYw_y59ohq69jNCW4sZQ',
    appId: '1:88197098485:android:e469787932f77eb0f10ebc',
    messagingSenderId: '88197098485',
    projectId: 'money-mate-608fd',
    storageBucket: 'money-mate-608fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6soyK9PmM_nwYg08IwByLbRkk8Gey3v8',
    appId: '1:88197098485:ios:3c58e74f36329d5bf10ebc',
    messagingSenderId: '88197098485',
    projectId: 'money-mate-608fd',
    storageBucket: 'money-mate-608fd.firebasestorage.app',
    iosBundleId: '1.moneyMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6soyK9PmM_nwYg08IwByLbRkk8Gey3v8',
    appId: '1:88197098485:ios:3c58e74f36329d5bf10ebc',
    messagingSenderId: '88197098485',
    projectId: 'money-mate-608fd',
    storageBucket: 'money-mate-608fd.firebasestorage.app',
    iosBundleId: '1.moneyMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLJ6Mr2QV9L2wry-hPXjxdfsd2qYEs2eM',
    appId: '1:88197098485:web:4700f39784a06e38f10ebc',
    messagingSenderId: '88197098485',
    projectId: 'money-mate-608fd',
    authDomain: 'money-mate-608fd.firebaseapp.com',
    storageBucket: 'money-mate-608fd.firebasestorage.app',
  );
}
